#!/bin/bash

# Define OS version
grep Ubuntu /etc/*-release > /dev/null && { installer="apt-get"; }
grep CentOS /etc/*-release > /dev/null && { installer="yum"; }

# chkconfig: 2345 90 10

# Source function library
if [ $installer == "yum" ]; then
	. /etc/init.d/functions
fi

### BEGIN INIT INFO
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=chat
DAEMON=/usr/bin/node
RUNFILE=/var/www/chat.io/index.js
PIDFILE=/var/run/$NAME.pid
LOCKFILE=/var/lock/subsys/$NAME
SCRIPTNAME=/etc/init.d/$NAME

# Function that starts the daemon/service
do_start() {
	if [ $installer == "yum" ]; then
		if [ ! -f $LOCK_FILE ]; then
			runuser -l $NAME -c $DAEMON $RUNFILE
			touch $LOCKFILE
		else
			exit 1
		fi
	else
		sudo start-stop-daemon -Sbmp $PIDFILE -x $DAEMON $RUNFILE
	fi
}

# Function that stops the daemon/service
do_stop() {
	if [ $installer == "yum" ]; then
		sudo kill -9 $DAEMON
		rm -f $LOCKFILE
	else
		sudo start-stop-daemon -Kp $PIDFILE
	fi
}

# Router
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 1
	;;
esac

exit $?
